### ISSUE TITLE
game doesn't load

### ISSUE THREAD

**Issue by kharandziuk** [Lallassu/VoxLords#2]
For some reasons game doesn't load. I use chromium browser on mac. I attached [an output from my console](http://pastebin.com/6ebVCQba)

**Comment by Lallassu** [comment]
Hm, strange. I just tested it on google-chrome on OS X and it worked fine. I haven't tested on pure chromium though. But try with google-chrome and see if that works?

Otherwise there might be some corruption of the sound files. Check that they are fine or just clone them from my repo again.

**Comment by harry-wood** [comment]
I'm trying this with Chrome v53.0.2785.101 (64-bit) on Mac today. The game scene appeared, but no movement. And it was logging _"three.min.js:517 Error creating WebGL context."_ 

but I saw a few other people reporting this problem with ThreeJS and there's a workaround here: https://github.com/mrdoob/three.js/issues/404#issuecomment-20466146 _"Enter in the location bar chrome://flags and enable Override software rendering list. Then restart the browser. WebGL now should work."_

However that's probably a different problem. kharandziuk was getting errors with sound file URLs (last year)

**Comment by Ithamar** [comment]
I had similar issues due to the server throwing an Exception and exiting, due to contentType being undefined  [here](https://github.com/Lallassu/VoxLords/blob/master/server/server.js#L84). Once I fixed that it all ran fine.
