### ISSUE TITLE
missing particleEngine.js

### ISSUE THREAD

**Issue by kevzettler** [Lallassu/VoxLords#3]
<img width="1280" alt="screenshot 2015-08-09 13 25 18" src="https://cloud.githubusercontent.com/assets/126209/9156765/258d2bf8-3e9a-11e5-862a-77979f3e6d7f.png">

not in the repo https://github.com/Lallassu/VoxLords/tree/master/js

Is it needed?

**Comment by Ithamar** [comment]
I can play through all 4 levels without seeing errors in the console or having the game fail on me, so I'm guessing the answer is: no it is not needed ;)
