### ISSUE TITLE
Doesn't capture the mouse movements in Safari

### ISSUE THREAD

**Issue by harry-wood** [Lallassu/VoxLords#6]
I tried this with Safari v9.1.3.  The game loads and I can start to play it. It does shoot when I click, but I realise it is supposed to capture mouse movements allowing me to steer. 

It logs this javascript error:
`instrClick — super-min.js:14:108649TypeError: a.requestPointerLock is not a function. (In 'a.requestPointerLock()', 'a.requestPointerLock' is undefined)`

(To be honest I was only trying in safari because chrome was giving me trouble. I normally expect chrome to cope better with webGL stuff. Just logging this issue in case others hit it)

**Comment by Ithamar** [comment]
I'll answer this for historical reasons, Safari 9 did not support PointerLock APIs, see [caniuse](https://caniuse.com/#search=pointerlock), it was only supported since 10.1
